default_stages: [commit, push]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: check-symlinks
      - id: detect-private-key
      - id: check-yaml
      - id: check-json
      - id: check-toml
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: no-go-testing
      - id: golangci-lint
        args: [--config=./.golangci.toml]
        stages: [push]
      - id: go-mod-tidy
      - id: go-generate
        args: [./...]
      - id: go-build
        stages: [push]
  - repo: local
    hooks:
      - id: go-tests
        name: go-tests
        entry: bash -c "make test-all | grep fail"
        language: system
        stages: [push]
