ignore_merge_commits = true
branch_whitelist = []
pre_bump_hooks = []
post_bump_hooks = []
from_latest_tag = true

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

ignore_commits = ["bc3dd03b02de598d4516b13edaa4c1d11d18dd2c"] # pragma: allowlist secret
