name: "Bench database/pginit"

on:
  push:
    paths:
      - "database/pginit/**"
      - ".github/workflows/**"
    branches: [main]

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.5"
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      # Run benchmark with `go test -bench` and stores the output to a file
      - name: Run benchmark
        working-directory: database/pginit
        env:
          GOPRIVATE: "github.com/induzo/*"
        run: |
          git config --global url.https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/.insteadOf https://github.com/
          go test ./... -bench=. -benchmem | tee ./bench-continuous.txt
      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "go"
          output-file-path: ./database/pginit/bench-continuous.txt
          # Workflow will fail when an alert happens
          fail-on-alert: false
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Enable alert commit comment
          comment-on-alert: true
          benchmark-data-dir-path: ./database/pginit/
          # When cache is used
          # external-data-json-path: ./cache/database/pginit/benchmark-data.json
          # Push and deploy GitHub pages branch automatically
          auto-push: true
