name: "Bench database/pginit"

on:
  push:
    paths:
      - "database/pginit/**"
      - ".github/workflows/database_pginit.bench.yml"
      - ".github/workflows/_bench.yml"
    branches: [main]

concurrency:
  group: bench-database-pginit-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  deployments: write

jobs:
  bench:
    uses: ./.github/workflows/_bench.yml
    with:
      module: database/pginit
    secrets: inherit
