name: "Bench database/pgx-slog"

on:
  push:
    paths:
      - "database/pgx-slog/**"
      - ".github/workflows/database_pgx-slog.bench.yml"
      - ".github/workflows/_bench.yml"
    branches: [main]

concurrency:
  group: bench-database-pgx-slog-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  deployments: write

jobs:
  bench:
    uses: ./.github/workflows/_bench.yml
    with:
      module: database/pgx-slog
    secrets: inherit
