name: "Bench http/health"

on:
  push:
    paths:
      - "http/health/**"
      - ".github/workflows/http_health.bench.yml"
      - ".github/workflows/_bench.yml"
    branches: [main]

concurrency:
  group: bench-http-health-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  deployments: write

jobs:
  bench:
    uses: ./.github/workflows/_bench.yml
    with:
      module: http/health
    secrets: inherit
