name: "Bench http/middleware/writablecontext"

on:
  push:
    paths:
      - "http/middleware/writablecontext/**"
      - ".github/workflows/http_middleware_writablecontext.bench.yml"
      - ".github/workflows/_bench.yml"
    branches: [main]

concurrency:
  group: bench-http-middleware-writablecontext-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  deployments: write

jobs:
  bench:
    uses: ./.github/workflows/_bench.yml
    with:
      module: http/middleware/writablecontext
    secrets: inherit
