name: "linter"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.21"
      - name: Cache golangci-lint
        id: golangci-lint
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/.cache/golangci-lint
          key: ${{ runner.os }}-golangci-lint-${{ hashFiles('go.work.sum') }}
          restore-keys: |
            ${{ runner.os }}-golangci-lint-
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install golangci-lint
        run: |
          VERSION=1.55.2
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/.local/bin v"$VERSION"
      - name: Lint all modules with golangci-lint
        run: |
          git config --global url."https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf "https://github.com"
          make lint-all
