name: "Bench shutdown"

on:
  push:
    paths:
      - "shutdown/**"
      - ".github/workflows/shutdown.bench.yml"
      - ".github/workflows/_bench.yml"
    branches: [main]

concurrency:
  group: bench-shutdown-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  deployments: write

jobs:
  bench:
    uses: ./.github/workflows/_bench.yml
    with:
      module: shutdown
    secrets: inherit
